CREATE TABLE IF NOT EXISTS manual_trade_orders (
    order_id CHAR(64) PRIMARY KEY,
    run_id VARCHAR(80) NOT NULL,
    stock_id INT UNSIGNED NOT NULL,
    side VARCHAR(4) NOT NULL,
    requested_date DATE NOT NULL,
    quantity INT UNSIGNED NOT NULL,
    target_price DECIMAL(14,4) NOT NULL,
    current_reference_price DECIMAL(14,4) NULL,
    entry_trade_id CHAR(64) NULL,
    reason VARCHAR(50) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    executed_trade_id CHAR(64) NULL,
    executed_date DATE NULL,
    last_checked_date DATE NULL,
    note VARCHAR(255) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_manual_trade_orders_status (status),
    KEY idx_manual_trade_orders_stock (stock_id),
    KEY idx_manual_trade_orders_requested_date (requested_date),
    CONSTRAINT fk_manual_trade_orders_run FOREIGN KEY (run_id) REFERENCES system_runs(run_id),
    CONSTRAINT fk_manual_trade_orders_stock FOREIGN KEY (stock_id) REFERENCES stocks(id),
    CONSTRAINT fk_manual_trade_orders_entry_trade FOREIGN KEY (entry_trade_id) REFERENCES paper_trades(trade_id),
    CONSTRAINT fk_manual_trade_orders_executed_trade FOREIGN KEY (executed_trade_id) REFERENCES paper_trades(trade_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
